#tasks to configure ntp client
- name: install chrony package
  ansible.builtin.yum:
    name: chrony
    state: present
  when: ansible_hostname != ntp.host.split('.')[0]

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "{{ ntp.time_zone|default('UTC') }}"
  when: ansible_hostname != ntp.host.split('.')[0]    

- name: set pool
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^pool'
    line: 'pool {{ ntp.pool|default("2.rhel.pool.ntp.org") }} iburst'
  register: update_ntp_server
  when: ansible_hostname != ntp.host.split('.')[0]

- name: add ntp server in config
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^server'
    line: 'server {{ ntp.host }} prefer'
  register: update_ntp_server
  when: ansible_hostname != ntp.host.split('.')[0]

- name: restart chrony server
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_hostname != ntp.host.split('.')[0] and update_ntp_server.changed
