#tasks to configure ntp server
- name: install chrony package
  ansible.builtin.yum:
    name: chrony
    state: present

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: "{{ ntp.time_zone|default('UTC') }}"

- name: allow access to client subnet
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^#allow'
    line: allow {{ network_subnet }}
  register: update_subnet

- name: set ntp pool
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: '^pool'
    line: pool {{ ntp.pool|default('2.rhel.pool.ntp.org') }} iburst
  register: update_pool

- name: restart chrony server
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: yes
  when: update_subnet.changed or update_pool.changed

- name: allow ntp service through firewall
  ansible.posix.firewalld:
    service: ntp
    permanent: yes
    immediate: yes
    state: enabled