---
# tasks file for openldap
- name: include tasks for configuring openldap server
  ansible.builtin.include_tasks:
    file: openldap-server.yml
    apply:
      tags: server
  tags:
    - never
    - server