---
# tasks file for kerberos
- name: include tasks for configuring kdc server
  ansible.builtin.include_tasks:
    file: kdc-kadmin-server.yml
    apply:
      tags: kdc-kadmin
  tags:
    - never
    - kdc-kadmin

- name: include tasks for managing principals
  ansible.builtin.include_tasks:
    file: principal-management.yml
    apply:
      tags: principals
  tags:
    - never
    - principals

- name: include tasks for configuring clients
  ansible.builtin.include_tasks:
    file: kerberos-client.yml
    apply:
      tags: client
  tags:
    - never
    - client

- name: include tasks for configuring sso enabled services
  ansible.builtin.include_tasks:
    file: sso-enabled-services.yml
    apply:
      tags: sso
  tags:
    - never
    - sso