- hosts: admin
  remote_user: root
  tasks:
    - name: include kerberos role
      ansible.builtin.include_role:
        name: kerberos
      tags:
        - never
        - kdc-kadmin
        - principals

- hosts: all
  remote_user: root
  tasks:
    - name: include kerberos role
      ansible.builtin.include_role:
        name: kerberos
      tags:
        - never
        - client
        - sso