- hosts: admin
  remote_user: root
  tasks:
    - name: include role private-dns
      ansible.builtin.include_role:
        name: private-dns
      tags:
        - never
        - server
        - records

- hosts: targets
  remote_user: root
  tasks:
    - name: include role private-dns
      ansible.builtin.include_role:
        name: private-dns
      tags:
        - never
        - client
