---
# tasks file for private-dns
- name: include tasks for configuring dns server
  ansible.builtin.include_tasks:
    file: dns-server.yml
    apply:
      tags: server
  tags:
    - never
    - server

- name: include tasks for configuring dns records
  ansible.builtin.include_tasks:
    file: dns-records.yml
    apply:
      tags: records
  tags:
    - never
    - records

- name: include tasks for configuring dns clients
  ansible.builtin.include_tasks:
    file: dns-client.yml
    apply:
      tags: client
  tags:
    - never
    - client